import { motion } from "framer-motion";
import SafetyGauge from "./SafetyGauge";
import { AlertTriangle, AlertCircle, Info, ShieldCheck } from "lucide-react";

export default function SummaryView({ report }) {
    const highRisks = report.red_flags.filter(f => f.risk_level === "High").length;
    const medRisks = report.red_flags.filter(f => f.risk_level === "Medium").length;
    const lowRisks = report.red_flags.filter(f => f.risk_level === "Low").length;

    return (
        <div className="max-w-6xl mx-auto p-8 space-y-12">

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
                {/* LEFT: SCORE CARD */}
                <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="bg-white border-3 border-ink shadow-brutal p-8"
                >
                    <SafetyGauge score={report.overall_risk_score} />
                </motion.div>

                {/* RIGHT: RISK BREAKDOWN */}
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.2 }}
                    className="grid grid-cols-3 gap-4 h-full"
                >
                    <RiskStatBox label="HIGH RISK" count={highRisks} color="bg-red-500" icon={<AlertTriangle className="w-8 h-8 text-white" />} />
                    <RiskStatBox label="MED RISK" count={medRisks} color="bg-yellow-400" icon={<AlertCircle className="w-8 h-8 text-black" />} />
                    <RiskStatBox label="LOW RISK" count={lowRisks} color="bg-blue-400" icon={<Info className="w-8 h-8 text-white" />} />
                </motion.div>
            </div>

            {/* EXECUTIVE SUMMARY */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-white border-3 border-ink shadow-brutal p-8 space-y-4"
            >
                <div className="flex items-center gap-3 border-b-3 border-ink pb-4">
                    <ShieldCheck className="w-8 h-8" />
                    <h2 className="text-3xl font-black uppercase tracking-tighter">Executive Summary</h2>
                </div>

                <div className="font-mono text-lg leading-relaxed space-y-4">
                    <p>{report.summary}</p>
                    <p className="text-gray-500 text-sm">
                        * This analysis was generated by AI and may highlight potential risks.
                        It is not a substitute for professional legal advice.
                    </p>
                </div>
            </motion.div>

        </div>
    );
}

function RiskStatBox({ label, count, color, icon }) {
    return (
        <div className={`border-3 border-ink shadow-brutal-sm p-4 flex flex-col items-center justify-between h-32 ${color}`}>
            <div className="mb-2">{icon}</div>
            <div className="text-4xl font-black text-white stroke-black" style={{ WebkitTextStroke: "1px black" }}>{count}</div>
            <div className="font-mono text-xs font-bold uppercase bg-white border-2 border-ink px-2 py-1 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                {label}
            </div>
        </div>
    );
}
